//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiComercial.wpEmpresasRelacionadas.wpEmpresasRelacionadas {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class wpEmpresasRelacionadas {
        
        protected global::System.Web.UI.WebControls.Label lbWarning1;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvWarning1;
        
        protected global::System.Web.UI.WebControls.Label lbEmpresa;
        
        protected global::System.Web.UI.WebControls.Label lbRut;
        
        protected global::System.Web.UI.WebControls.Label lbEjecutivo;
        
        protected global::System.Web.UI.WebControls.LinkButton lbDatosEmpresa;
        
        protected global::System.Web.UI.WebControls.LinkButton lbHistoria;
        
        protected global::System.Web.UI.WebControls.LinkButton lbDocumentos;
        
        protected global::System.Web.UI.WebControls.LinkButton lbEmpresaRelacionada;
        
        protected global::System.Web.UI.WebControls.LinkButton lbDireccion;
        
        protected global::System.Web.UI.WebControls.LinkButton lbPersonas;
        
        protected global::System.Web.UI.WebControls.Label lbSuccess;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvSuccess;
        
        protected global::System.Web.UI.WebControls.Label lbWarning;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvWarning;
        
        protected global::System.Web.UI.WebControls.Label lbError;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvError;
        
        protected global::System.Web.UI.WebControls.TextBox txt_rut;
        
        protected global::System.Web.UI.WebControls.TextBox txt_divRut;
        
        protected global::System.Web.UI.WebControls.LinkButton btnBuscarEmpresa;
        
        protected global::System.Web.UI.WebControls.TextBox txt_nombre;
        
        protected global::System.Web.UI.WebControls.TextBox txt_nroDocProtestos;
        
        protected global::System.Web.UI.WebControls.TextBox txt_MontoProtestos;
        
        protected global::System.Web.UI.WebControls.TextBox txt_nroDocMorosidades;
        
        protected global::System.Web.UI.WebControls.TextBox txt_montoMorosidades;
        
        protected global::System.Web.UI.WebControls.TextBox txt_tipo;
        
        protected global::System.Web.UI.WebControls.TextBox txt_patrimonio;
        
        protected global::System.Web.UI.WebControls.TextBox txt_montoInfraccionesLab;
        
        protected global::System.Web.UI.WebControls.TextBox txt_montoInfraccionesPrev;
        
        protected global::System.Web.UI.WebControls.Panel pnFormulario;
        
        protected global::System.Web.UI.WebControls.Button btnAtras;
        
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        
        protected global::System.Web.UI.WebControls.GridView ResultadosBusqueda;
        
        protected global::System.Web.UI.WebControls.HiddenField HddIdEmpresaRelacionada;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvFormulario;
        
        public static implicit operator global::System.Web.UI.TemplateControl(wpEmpresasRelacionadas target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbWarning1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbWarning1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbWarning1";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvWarning1() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvWarning1 = @__ctrl;
            @__ctrl.ID = "dvWarning1";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-warning");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("role", "alert");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <h4>\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbWarning1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </h4>\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbEmpresa() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbEmpresa = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbEmpresa";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbRut() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbRut = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbRut";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbEjecutivo() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbEjecutivo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbEjecutivo";
            @__ctrl.Text = " ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbDatosEmpresa() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbDatosEmpresa = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbDatosEmpresa";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Datos Empresa"));
            @__ctrl.Click -= new System.EventHandler(this.lbDatosEmpresa_Click);
            @__ctrl.Click += new System.EventHandler(this.lbDatosEmpresa_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbHistoria() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbHistoria = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbHistoria";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Historia Empresa"));
            @__ctrl.Click -= new System.EventHandler(this.lbHistoria_Click);
            @__ctrl.Click += new System.EventHandler(this.lbHistoria_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbDocumentos() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbDocumentos = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbDocumentos";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Documentos"));
            @__ctrl.Click -= new System.EventHandler(this.lbDocumentos_Click);
            @__ctrl.Click += new System.EventHandler(this.lbDocumentos_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbEmpresaRelacionada() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbEmpresaRelacionada = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbEmpresaRelacionada";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Empresas Relacionadas"));
            @__ctrl.Click -= new System.EventHandler(this.lbEmpresaRelacionada_Click);
            @__ctrl.Click += new System.EventHandler(this.lbEmpresaRelacionada_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbDireccion() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbDireccion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbDireccion";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Direcciones"));
            @__ctrl.Click -= new System.EventHandler(this.lbDireccion_Click);
            @__ctrl.Click += new System.EventHandler(this.lbDireccion_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbPersonas() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbPersonas = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbPersonas";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Personas"));
            @__ctrl.Click -= new System.EventHandler(this.lbPersonas_Click);
            @__ctrl.Click += new System.EventHandler(this.lbPersonas_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbSuccess() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbSuccess = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbSuccess";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvSuccess() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvSuccess = @__ctrl;
            @__ctrl.ID = "dvSuccess";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-success");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <h4>\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbSuccess();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </h4>\r\n                "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbWarning() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbWarning = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbWarning";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvWarning() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvWarning = @__ctrl;
            @__ctrl.ID = "dvWarning";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-warning");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <h4>\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbWarning();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </h4>\r\n                "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbError";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvError() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvError = @__ctrl;
            @__ctrl.ID = "dvError";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-danger");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <h4>\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbError();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </h4>\r\n                "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_rut() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_rut = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_rut";
            @__ctrl.MaxLength = 8;
            @__ctrl.CssClass = "form-control";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width:100%;");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onKeyPress", "return solonumeros(event)");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_divRut() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_divRut = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_divRut";
            @__ctrl.MaxLength = 1;
            @__ctrl.CssClass = "form-control";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onKeyPress", "return solonumerosDV(event)");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlbtnBuscarEmpresa() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.btnBuscarEmpresa = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnBuscarEmpresa";
            @__ctrl.Text = "Buscar";
            @__ctrl.CssClass = "btn btn-default";
            @__ctrl.OnClientClick = " return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                                    <i class=\"f" +
                        "a fa-search\"></i>\r\n                                                             " +
                        "   "));
            @__ctrl.Click -= new System.EventHandler(this.btnBuscarEmpresa_Click);
            @__ctrl.Click += new System.EventHandler(this.btnBuscarEmpresa_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_nombre() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_nombre = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_nombre";
            @__ctrl.CssClass = "form-control";
            @__ctrl.Enabled = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_nroDocProtestos() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_nroDocProtestos = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_nroDocProtestos";
            @__ctrl.CssClass = "form-control";
            @__ctrl.MaxLength = 16;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_MontoProtestos() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_MontoProtestos = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_MontoProtestos";
            @__ctrl.CssClass = "form-control";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onKeyPress", "return solonumeros(event)");
            @__ctrl.MaxLength = 16;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_nroDocMorosidades() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_nroDocMorosidades = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_nroDocMorosidades";
            @__ctrl.CssClass = "form-control";
            @__ctrl.MaxLength = 16;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_montoMorosidades() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_montoMorosidades = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_montoMorosidades";
            @__ctrl.CssClass = "form-control";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onKeyPress", "return solonumeros(event)");
            @__ctrl.MaxLength = 16;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_tipo() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_tipo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_tipo";
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_patrimonio() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_patrimonio = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_patrimonio";
            @__ctrl.CssClass = "form-control";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onKeyPress", "return solonumeros(event)");
            @__ctrl.MaxLength = 16;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_montoInfraccionesLab() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_montoInfraccionesLab = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_montoInfraccionesLab";
            @__ctrl.CssClass = "form-control";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onKeyPress", "return solonumeros(event)");
            @__ctrl.MaxLength = 16;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxt_montoInfraccionesPrev() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txt_montoInfraccionesPrev = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txt_montoInfraccionesPrev";
            @__ctrl.CssClass = "form-control";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onKeyPress", "return solonumeros(event)");
            @__ctrl.MaxLength = 16;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnFormulario() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnFormulario = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnFormulario";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <!-- Grupo 1 -->
                                <div class=""col-md-6"">
                                    <div class=""form-group row"">
                                        <label for=""inputPassword3"" class=""col-sm-5 control-label"">RUT:</label>
                                        <div class=""col-sm-7"">
                                            <table style=""width:100%;"">
                                                <tr>
                                                    <td  style=""width:70%;"">
                                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxt_rut();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                    </td>
                                                    <td>&nbsp;</td>
                                                    <td>
                                                        <div class=""input-group"">
                                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxt_divRut();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                            <span style=""color: red;"" id=""errorRut""></span>
                                                            <span class=""input-group-btn"">
                                                                "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl3;
            @__ctrl3 = this.@__BuildControlbtnBuscarEmpresa();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                            </span>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>

                                    <div class=""form-group row"">
                                        <label for=""inputEmail3"" class=""col-sm-5 control-label"">Nombre o Razón Social:</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxt_nombre();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <label for=""inputPassword3"" class=""col-sm-5 control-label"">Nro. Doc. Protestos:</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            @__ctrl5 = this.@__BuildControltxt_nroDocProtestos();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <label for=""inputPassword3"" class=""col-sm-5 control-label"">Monto Protestos:</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxt_MontoProtestos();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <label for=""inputPassword3"" class=""col-sm-5 control-label"">Nro. Doc. Morosidades:</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            @__ctrl7 = this.@__BuildControltxt_nroDocMorosidades();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <label for=""inputPassword3"" class=""col-sm-5 control-label"">Monto Morosidades:</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            @__ctrl8 = this.@__BuildControltxt_montoMorosidades();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                </div>
                                <!-- Grupo 2 -->
                                <div class=""col-md-6"">
                                    <div class=""form-group row"">
                                        <label for=""inputEmail3"" class=""col-sm-5 control-label"">Tipo Relación:</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            @__ctrl9 = this.@__BuildControltxt_tipo();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <label for=""inputPassword3"" class=""col-sm-5 control-label"">Patrimonio ($MM):</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            @__ctrl10 = this.@__BuildControltxt_patrimonio();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <label for=""inputPassword3"" class=""col-sm-5 control-label"">Monto Infracciones Laborales:</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl11;
            @__ctrl11 = this.@__BuildControltxt_montoInfraccionesLab();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <label for=""inputPassword3"" class=""col-sm-5 control-label"">Monto Infracciones Previsionales:</label>
                                        <div class=""col-sm-7"">
                                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            @__ctrl12 = this.@__BuildControltxt_montoInfraccionesPrev();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        </div>\r\n                               " +
                        "     </div>\r\n                                </div>\r\n                           " +
                        " "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnAtras() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnAtras = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnAtras";
            @__ctrl.CssClass = "btn btn-default pull-left";
            @__ctrl.Text = " < Volver Atrás";
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnAtras_Click);
            @__ctrl.Click += new System.EventHandler(this.btnAtras_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancelar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancelar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancelar";
            @__ctrl.Text = "Cancelar";
            @__ctrl.CssClass = "btn btn-primary pull-right";
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnAtras_Click);
            @__ctrl.Click += new System.EventHandler(this.btnAtras_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel";
            @__ctrl.Text = "Limpiar";
            @__ctrl.CssClass = "btn btn-warning pull-right";
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnGuardar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnGuardar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.CssClass = "btn btn-primary btn-success pull-right";
            @__ctrl.ID = "btnGuardar";
            @__ctrl.Text = "Guardar";
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnGuardar_Click);
            @__ctrl.Click += new System.EventHandler(this.btnGuardar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlResultadosBusqueda() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.ResultadosBusqueda = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ResultadosBusqueda";
            @__ctrl.CssClass = "table table-bordered table-hover";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Horizontal;
            @__ctrl.ShowHeaderWhenEmpty = true;
            @__ctrl.RowCreated -= new System.Web.UI.WebControls.GridViewRowEventHandler(this.ResultadosBusqueda_RowCreated);
            @__ctrl.RowCreated += new System.Web.UI.WebControls.GridViewRowEventHandler(this.ResultadosBusqueda_RowCreated);
            @__ctrl.RowDataBound -= new System.Web.UI.WebControls.GridViewRowEventHandler(this.ResultadosBusqueda_RowDataBound);
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.ResultadosBusqueda_RowDataBound);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHddIdEmpresaRelacionada() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.HddIdEmpresaRelacionada = @__ctrl;
            @__ctrl.ID = "HddIdEmpresaRelacionada";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvFormulario() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvFormulario = @__ctrl;
            @__ctrl.ID = "dvFormulario";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<!-- Page-Title -->
<div class=""row marginInicio"">
    <div class=""col-sm-12"">
        <h4 class=""page-title"">Documentos</h4>
        <ol class=""breadcrumb"">
            <li>
                <a href=""#"">Datos Empresa</a>
            </li>
            <li class=""active"">Empresas Relacionadas
            </li>
        </ol>
    </div>
</div>

 <!-- Empresa -->
 <div class=""row"">
    <div class=""col-md-12"">
        <div class=""alert alert-gray"">
            <p>
                <strong>Empresa:
                "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbEmpresa();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</strong> /\r\n                "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllbRut();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                \r\n                / Ejecutivo:\r\n                "));
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControllbEjecutivo();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
            </p>
        </div>
    </div>
</div>


<!-- Contenedor Tabs -->
<div class=""row"">
    <div class=""col-md-12"">
        <ul class=""nav nav-tabs navtab-bg nav-justified"">
            <li class="""">
                <a href=""#tab1"" data-toggle=""tab"" aria-expanded=""false"">
                    <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                    <span class=""hidden-xs"">
                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl4;
            @__ctrl4 = this.@__BuildControllbDatosEmpresa();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                    </span>
                </a>
            </li>
            <li class="""">
                <a href=""#tab2"" data-toggle=""tab"" aria-expanded=""false"">
                    <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                    <span class=""hidden-xs"">
                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl5;
            @__ctrl5 = this.@__BuildControllbHistoria();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                    </span>
                </a>
            </li>
            <li class="""">
                <a href=""#tab3"" data-toggle=""tab"" aria-expanded=""false"">
                    <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                    <span class=""hidden-xs"">
                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl6;
            @__ctrl6 = this.@__BuildControllbDocumentos();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                    </span>
                </a>
            </li>
            <li class=""active"">
                <a href=""#tab4"" data-toggle=""tab"" aria-expanded=""true"">
                    <span class=""visible-xs""><i class=""fa fa-home""></i></span>
                    <span class=""hidden-xs"">
                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl7;
            @__ctrl7 = this.@__BuildControllbEmpresaRelacionada();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                    </span>
                </a>
            </li>
            <li class="""">
                <a href=""#tab5"" data-toggle=""tab"" aria-expanded=""false"">
                    <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                    <span class=""hidden-xs"">
                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl8;
            @__ctrl8 = this.@__BuildControllbDireccion();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                    </span>
                </a>
            </li>
            <li class="""">
                <a href=""#tab6"" data-toggle=""tab"" aria-expanded=""false"">
                    <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                    <span class=""hidden-xs"">
                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl9;
            @__ctrl9 = this.@__BuildControllbPersonas();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </span>\r\n                </a>\r\n            </li>\r\n        <" +
                        "/ul>\r\n\r\n        <div class=\"tab-content\">\r\n            <div class=\"tab-pane acti" +
                        "ve\" id=\"tab4\">\r\n\r\n                "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl10;
            @__ctrl10 = this.@__BuildControldvSuccess();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl11;
            @__ctrl11 = this.@__BuildControldvWarning();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl12;
            @__ctrl12 = this.@__BuildControldvError();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <div class=\"row\">\r\n\t\t\t\t\t<div class=\"col-md-12\">\r\n\t\t\t\t\t\t\t<div cl" +
                        "ass=\"card-box\">\r\n\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t"));
            global::System.Web.UI.WebControls.Panel @__ctrl13;
            @__ctrl13 = this.@__BuildControlpnFormulario();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n                <table wi" +
                        "dth=\"100%\">\r\n                    <tr>\r\n                        <td>\r\n           " +
                        "                 "));
            global::System.Web.UI.WebControls.Button @__ctrl14;
            @__ctrl14 = this.@__BuildControlbtnAtras();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </td>\r\n\r\n                        <td>\r\n                " +
                        "            "));
            global::System.Web.UI.WebControls.Button @__ctrl15;
            @__ctrl15 = this.@__BuildControlbtnCancelar();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                            "));
            global::System.Web.UI.WebControls.Button @__ctrl16;
            @__ctrl16 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                            "));
            global::System.Web.UI.WebControls.Button @__ctrl17;
            @__ctrl17 = this.@__BuildControlbtnGuardar();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </td>
                    </tr>
                </table>
                <BR>
               <!-- tabla / grilla -->
                <div class=""row"">
                    <div class=""col-md-12"">
                        <table border=""0"" style=""table-layout:fixed; width:100%;"">
                            <tr>
                                <td>
                                    <div class=""card-box"">
                                        <div class=""table-responsive"">
                                            <div class=""row"">
                                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl18;
            @__ctrl18 = this.@__BuildControlResultadosBusqueda();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

"));
            global::System.Web.UI.WebControls.HiddenField @__ctrl19;
            @__ctrl19 = this.@__BuildControlHddIdEmpresaRelacionada();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::MultiComercial.wpEmpresasRelacionadas.wpEmpresasRelacionadas.wpEmpresasRelacionadas @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<style type=\"text/css\">\r\n    .form-group label {\r\n        text-align:right;\r\n  " +
                        "      padding-top:10px;\r\n    }\r\n</style>\r\n<link href=\"../../_layouts/15/MultiCom" +
                        "ercial/jquery-ui.css\" rel=\"stylesheet\" />\r\n<script src=\"../../_layouts/15/MultiC" +
                        "omercial/jquery-1.11.1.js\"></script>\r\n<script src=\"../../_layouts/15/MultiComerc" +
                        "ial/jquery-ui.js\"></script>\r\n<script src=\"../../_layouts/15/MultiComercial/jquer" +
                        "y.Rut.js\"></script>\r\n<script src=\"../../_layouts/15/MultiComercial/jquery.mask.j" +
                        "s\"></script>\r\n\r\n<script src=\"../../_layouts/15/MultiComercial/wpEmpresasRelacion" +
                        "adas.js\"></script>\r\n\r\n<script type=\"text/javascript\">\r\n    document.onkeydown = " +
                        "function () {\r\n        //109->\'-\' \r\n        //56->\'(\' \r\n        if (window.event" +
                        " && (window.event.keyCode == 109 || window.event.keyCode == 56)) {\r\n            " +
                        "window.event.keyCode = 505;\r\n        }\r\n\r\n        if (window.event.keyCode == 50" +
                        "5) {\r\n            return false;\r\n        }\r\n\r\n        if (window.event && (windo" +
                        "w.event.keyCode == 8)) {\r\n            valor = document.activeElement.value;\r\n   " +
                        "         if (valor == undefined) { return false; } //Evita Back en página. \r\n\r\n " +
                        "           else {\r\n                if (document.activeElement.getAttribute(\'type" +
                        "\') == \'select-one\')\r\n                { return false; } //Evita Back en select. \r" +
                        "\n                if (document.activeElement.getAttribute(\'type\') == \'button\')\r\n " +
                        "               { return false; } //Evita Back en button. \r\n                if (d" +
                        "ocument.activeElement.getAttribute(\'type\') == \'radio\')\r\n                { return" +
                        " false; } //Evita Back en radio. \r\n                if (document.activeElement.ge" +
                        "tAttribute(\'type\') == \'checkbox\')\r\n                { return false; } //Evita Bac" +
                        "k en checkbox. \r\n                if (document.activeElement.getAttribute(\'type\')" +
                        " == \'file\')\r\n                { return false; } //Evita Back en file. \r\n         " +
                        "       if (document.activeElement.getAttribute(\'type\') == \'reset\')\r\n            " +
                        "    { return false; } //Evita Back en reset. \r\n                if (document.acti" +
                        "veElement.getAttribute(\'type\') == \'submit\')\r\n                { return false; } /" +
                        "/Evita Back en submit. \r\n                if (document.activeElement.getAttribute" +
                        "(\'type\') == \'input\')\r\n                { return false; } //Evita Back en inout. \r" +
                        "\n                else //Text, textarea o password \r\n                {\r\n         " +
                        "           if (document.activeElement.value.length == 0)\r\n                    { " +
                        "return false; } //No realiza el backspace(largo igual a 0). \r\n                  " +
                        "  else {\r\n                        document.activeElement.value.keyCode = 8;\r\n   " +
                        "                 } //Realiza el backspace. \r\n                }\r\n            }\r\n\r" +
                        "\n            if (window.event && (window.event.keyCode == 13)) {\r\n              " +
                        "  valor = document.activeElement.value;\r\n                if (valor == undefined)" +
                        " { return false; } //Evita Enter en página. \r\n                else {\r\n          " +
                        "          if (document.activeElement.getAttribute(\'type\') == \'select-one\')\r\n    " +
                        "                { return false; } //Evita Enter en select. \r\n                   " +
                        " if (document.activeElement.getAttribute(\'type\') == \'button\')\r\n                 " +
                        "   { return false; } //Evita Enter en button. \r\n                    if (document" +
                        ".activeElement.getAttribute(\'type\') == \'radio\')\r\n                    { return fa" +
                        "lse; } //Evita Enter en radio. \r\n                    if (document.activeElement." +
                        "getAttribute(\'type\') == \'checkbox\')\r\n                    { return false; } //Evi" +
                        "ta Enter en checkbox. \r\n                    if (document.activeElement.getAttrib" +
                        "ute(\'type\') == \'file\')\r\n                    { return false; } //Evita Enter en f" +
                        "ile. \r\n                    if (document.activeElement.getAttribute(\'type\') == \'r" +
                        "eset\')\r\n                    { return false; } //Evita Enter en reset. \r\n        " +
                        "            if (document.activeElement.getAttribute(\'type\') == \'submit\')\r\n      " +
                        "              { return false; } //Evita Enter en submit. \r\n                    i" +
                        "f (document.activeElement.getAttribute(\'type\') == \'input\')\r\n                    " +
                        "{ return false; } //Evita Back en input. \r\n                    else //Text, text" +
                        "area o password \r\n                    {\r\n                        if (document.ac" +
                        "tiveElement.value.length == 0)\r\n                        { return false; } //No r" +
                        "ealiza el backspace(largo igual a 0). \r\n                        //else {\r\n      " +
                        "                  //    document.activeElement.value.keyCode = 13;\r\n            " +
                        "            //} //Realiza el enter. \r\n                    }\r\n                }\r\n" +
                        "            }\r\n        }\r\n    }\r\n\r\n</script>\r\n\r\n\r\n"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldvWarning1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControldvFormulario();
            @__parser.AddParsedSubObject(@__ctrl2);
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
