//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiComercial.newTest.wpNewTest {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class wpNewTest {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(wpNewTest target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::MultiComercial.newTest.wpNewTest.wpNewTest @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <body class=\"fixed-left\">\r\n\r\n        <!-- Begin page -->\r\n        <div id" +
                        "=\"wrapper\">\r\n\r\n            <!-- Top Bar Start -->\r\n\r\n            <!-- ==========" +
                        " Left Sidebar Start ========== -->\r\n\r\n\r\n            <!-- Left Sidebar End -->\r\n\r" +
                        "\n\r\n\r\n            <!-- ==========================================================" +
                        "==== -->\r\n            <!-- Cuerpo -->\r\n            <!-- ========================" +
                        "====================================== -->\r\n            <div class=\"content-page" +
                        "\" style=\"margin-left:0px;\">\r\n                <!-- Start content -->\r\n           " +
                        "     <div class=\"content\">\r\n                    <div class=\"container\">\r\n\r\n     " +
                        "                   <!-- Page-Title -->\r\n                        <div class=\"row " +
                        "marginInicio\">\r\n                            <div class=\"col-sm-12\">\r\n           " +
                        "                     <h4 class=\"page-title\">Comercial</h4>\r\n                    " +
                        "            <ol class=\"breadcrumb\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Inicio" +
                        "</a>\r\n\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\t<li class=\"active\">\r\n\t\t\t\t\t\t\t\t\t\tComercial\r\n\t\t\t\t\t\t\t" +
                        "\t\t</li>\r\n\t\t\t\t\t\t\t\t</ol>\r\n                            </div>\r\n                    " +
                        "    </div>\r\n\r\n                        <!-- botones -->\r\n                        " +
                        "<!--div class=\"row\">\r\n\t                        <div class=\"col-md-12 text-right\"" +
                        ">\r\n                                <div class=\"card-box\">\r\n    \t                " +
                        "        \t<button type=\"button\" class=\"btn btn-default\">\r\n                       " +
                        "         \t</span>Compromisos Semanal</button>\r\n                                \t" +
                        "<button type=\"button\" class=\"btn btn-default\">\r\n                                " +
                        "\t<span class=\"btn-label\"><i class=\"fa fa-plus\"></i>\r\n                           " +
                        "     \t</span>Crear Nueva Empresa</button>\r\n                                </div" +
                        ">\r\n                            </div>\r\n                        </div-->\r\n\r\n\t\t\t\t\t" +
                        "\t\r\n\t\t\t\t\t\t<!-- CABECERA ERG.22-09-2016 -->\r\n\t\t\t\t\t\t\t<!-- filtros-->\r\n\t\t\t\t\t\t\t<div c" +
                        "lass=\"row\">\r\n\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"card-box\">\r\n\t" +
                        "\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6" +
                        "\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"\">Buscar</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-grou" +
                        "p\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"\" name=\"\" class=\"form-control\" placeholder=\"Buscar\"" +
                        " type=\"text\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-btn\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<button" +
                        " type=\"button\" class=\"btn btn-default\"><i class=\"fa fa-search\"></i></button>\r\n\t\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t</span>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class" +
                        "=\"col-md-3 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"\">Estado</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<se" +
                        "lect class=\"form-control\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option>- Seleccionar Estado -</option>" +
                        "\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option>1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option>2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t" +
                        "\t<option>3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<div c" +
                        "lass=\"col-md-3 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label>Etapa</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<select" +
                        " class=\"form-control\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option>- Seleccionar Etapa -</option>\r\n\t\t\t" +
                        "\t\t\t\t\t\t\t\t\t\t<option>1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option>2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<opt" +
                        "ion>3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=" +
                        "\"col-md-3 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label>SubEtapa</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<select c" +
                        "lass=\"form-control\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option>- Seleccionar SubEtapa -</option>\r\n\t\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t<option>1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<option>2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<op" +
                        "tion>3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t" +
                        "</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<!-- END CABECERA " +
                        "ERG.22-09-2016 -->\r\n\t\t\t\t\t\t\r\n                        <!-- tabla / grilla -->\r\n   " +
                        "                     <div class=\"row\">            \t\t\t\t\t\t\r\n                      " +
                        "  \t<div class=\"col-md-12\">\r\n                        \t\t<div class=\"card-box\">\r\n  " +
                        "                      \t\t\t<div class=\"table-responsive\">\r\n\t                      " +
                        "  \t\t\t<table class=\"table table-bordered table-hover\">\r\n\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n\t\t\t\t\t" +
                        "\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tCliente\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t" +
                        "\t\t\t\t\t\t\t\t<th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tOperación\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>\r\n\t\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t\tMonto\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tEtapa\r\n\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tSubEtapa\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</th>" +
                        "\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tEstado\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>" +
                        "\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tDatos Empresa\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>\r\n\t\t\t\t\t\t\t\t\t\t" +
                        "\t\t\t\tDatos Operación\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tDatos " +
                        "Adm. Empresa\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tAcción\r\n\t\t\t\t\t" +
                        "\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n\t\t\t\t\t" +
                        "\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\" class=\"text-custom\"><i " +
                        "class=\"glyphicon glyphicon-plus-sign\" data-toggle=\"tooltip\" data-placement=\"top\"" +
                        " data-original-title=\"Agregar un negocio\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tSociedad Agríc" +
                        "ola Montero y Montero Limitada\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t" +
                        "\t\t\t\t\t5452 - Certificado Fianza Comercial\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r" +
                        "\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tCLP 216.000.000\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t" +
                        "\t\t\t\t\tProspecto\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class" +
                        "=\"label label-inverse\">Caducado</span>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t\t\tIngresado\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a " +
                        "href=\"\" class=\"text-custom\"><i class=\"md md-info-outline padIconos\" data-toggle=" +
                        "\"tooltip\" data-placement=\"top\" data-original-title=\"Información de la Empresa\"><" +
                        "/i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\" class=\"text-custom\"><i class=\"md md-assignment" +
                        " padIconos\" data-toggle=\"tooltip\" data-placement=\"top\" data-original-title=\"Hist" +
                        "oria Empresa\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\" class=\"text-custom\"><i class=\"m" +
                        "d md-business padIconos\" data-toggle=\"tooltip\" data-placement=\"top\" data-origina" +
                        "l-title=\"Empresas Relacionadas\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\" class=\"text-c" +
                        "ustom\"><i class=\"md md-loop padIconos\" data-toggle=\"tooltip\" data-placement=\"top" +
                        "\" data-original-title=\"Socios y Asociados\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\" cl" +
                        "ass=\"text-custom\"><i class=\"md md-work padIconos\" data-toggle=\"tooltip\" data-pla" +
                        "cement=\"top\" data-original-title=\"Directorio\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t" +
                        "\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\" class=\"text-custom\"><i class=\"md md-loca" +
                        "l-atm padIconos\" data-toggle=\"tooltip\" data-placement=\"top\" data-original-title=" +
                        "\"Garantías\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\" class=\"text-custom\"><i class=\"md " +
                        "md-folder-open padIconos\" data-toggle=\"tooltip\" data-placement=\"top\" data-origin" +
                        "al-title=\"Documentos\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\" class=\"text-custom\"><i " +
                        "class=\"ion-gear-b padIconos\" data-toggle=\"tooltip\" data-placement=\"top\" data-ori" +
                        "ginal-title=\"Configuración\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\r\n\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td" +
                        ">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t" +
                        "\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t" +
                        "\t\t\t\t\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t[Conte" +
                        "nido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t" +
                        "\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<t" +
                        "d>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t" +
                        "\t\t\t\t[Contenido]\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n\t\t\t" +
                        "\t\t\t\t\t\t\t</table>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n                        \t\t</div>\r\n            " +
                        "            \t</div>\r\n                        </div>\r\n                        <!-" +
                        "- end row -->\r\n\r\n                    </div> <!-- container -->\r\n\r\n              " +
                        "  </div> <!-- content -->\r\n            </div>\r\n\r\n\r\n            <!-- ============" +
                        "================================================== -->\r\n            <!-- End Rig" +
                        "ht content here -->\r\n            <!-- ==========================================" +
                        "==================== -->\r\n\r\n        </div>\r\n        <!-- END wrapper -->\r\n\r\n    " +
                        "</body>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
