//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiRiesgo.wpDetalleCarteraMorosos.DetalleCarteraMorosos {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class DetalleCarteraMorosos {
        
        protected global::System.Web.UI.WebControls.Label lbWarning1;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvWarning1;
        
        protected global::System.Web.UI.WebControls.TextBox txtEmpresa;
        
        protected global::System.Web.UI.WebControls.TextBox txtNroCertificado;
        
        protected global::System.Web.UI.WebControls.TextBox txtFondo;
        
        protected global::System.Web.UI.WebControls.TextBox txtDiasMora;
        
        protected global::System.Web.UI.WebControls.TextBox txtCapital;
        
        protected global::System.Web.UI.WebControls.TextBox txtMontoMora;
        
        protected global::System.Web.UI.WebControls.TextBox txtCuotasPagadas;
        
        protected global::System.Web.UI.WebControls.TextBox txtSaldoCertificado;
        
        protected global::System.Web.UI.WebControls.TextBox txtFogape;
        
        protected global::System.Web.UI.WebControls.TextBox txtDeudaCF;
        
        protected global::System.Web.UI.WebControls.TextBox txtGiro;
        
        protected global::System.Web.UI.WebControls.TextBox txtAcreedor;
        
        protected global::System.Web.UI.WebControls.TextBox txtTramo;
        
        protected global::System.Web.UI.WebControls.TextBox txtIntereses;
        
        protected global::System.Web.UI.WebControls.TextBox txtCuotasMora;
        
        protected global::System.Web.UI.WebControls.TextBox txtCuotasPactadas;
        
        protected global::System.Web.UI.WebControls.TextBox TextBox2;
        
        protected global::System.Web.UI.WebControls.TextBox txtGarantia;
        
        protected global::System.Web.UI.WebControls.TextBox TextBox3;
        
        protected global::System.Web.UI.WebControls.TextBox txtCobertura;
        
        protected global::System.Web.UI.WebControls.GridView gridContactos;
        
        protected global::System.Web.UI.WebControls.Button btnAtras;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvFormulario;
        
        public static implicit operator global::System.Web.UI.TemplateControl(DetalleCarteraMorosos target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbWarning1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbWarning1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbWarning1";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvWarning1() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvWarning1 = @__ctrl;
            @__ctrl.ID = "dvWarning1";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-warning");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("role", "alert");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n     <h4>\r\n         "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbWarning1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </h4>\r\n "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEmpresa() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEmpresa = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEmpresa";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtNroCertificado() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtNroCertificado = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtNroCertificado";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtFondo() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtFondo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtFondo";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtDiasMora() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtDiasMora = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtDiasMora";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCapital() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtCapital = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtCapital";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtMontoMora() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtMontoMora = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtMontoMora";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCuotasPagadas() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtCuotasPagadas = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtCuotasPagadas";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSaldoCertificado() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSaldoCertificado = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtSaldoCertificado";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtFogape() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtFogape = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtFogape";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtDeudaCF() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtDeudaCF = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtDeudaCF";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtGiro() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtGiro = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtGiro";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtAcreedor() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtAcreedor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtAcreedor";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTramo() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtTramo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtTramo";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtIntereses() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtIntereses = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtIntereses";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCuotasMora() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtCuotasMora = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtCuotasMora";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCuotasPactadas() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtCuotasPactadas = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtCuotasPactadas";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTextBox2() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.TextBox2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "TextBox2";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtGarantia() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtGarantia = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtGarantia";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTextBox3() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.TextBox3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "TextBox3";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCobertura() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtCobertura = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtCobertura";
            @__ctrl.CssClass = "form-control";
            @__ctrl.ReadOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgridContactos() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.gridContactos = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "gridContactos";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Horizontal;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "table table-bordered table-hovered");
            @__ctrl.RowHeaderColumn = "0";
            @__ctrl.ShowHeaderWhenEmpty = true;
            @__ctrl.PageSize = 10;
            @__ctrl.PageIndexChanging -= new System.Web.UI.WebControls.GridViewPageEventHandler(this.gridContactos_PageIndexChanging);
            @__ctrl.PageIndexChanging += new System.Web.UI.WebControls.GridViewPageEventHandler(this.gridContactos_PageIndexChanging);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnAtras() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnAtras = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnAtras";
            @__ctrl.CssClass = "btn btn-default pull-left";
            @__ctrl.Text = " < Volver Atrás";
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnAtras_Click);
            @__ctrl.Click += new System.EventHandler(this.btnAtras_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvFormulario() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvFormulario = @__ctrl;
            @__ctrl.ID = "dvFormulario";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

    <!-- Page-Title -->
    <div class=""row marginInicio"">
        <div class=""col-sm-12"">
            <h4 class=""page-title"">Riesgo</h4>
            <ol class=""breadcrumb"">
                <li>
                    <a href=""#"">Detalle Cartera Morosos</a>
                </li>
                <li class=""active"">Detalle Cartera Morosos</li>
            </ol>
        </div>
    </div>


    <div class=""row"">
        <div class=""col-md-12"">
            <div class=""card-box"">
                <div class=""row"">
                    <div class=""col-md-12 col-sm-12"">
                        <h4>Detale Certificado</h4>
                    </div>

                    <div class=""form-horizontal"" role=""form"">
                        <div class=""col-md-6"">
                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Empresa</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtEmpresa();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                           

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">N° Certificado</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxtNroCertificado();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Fondo</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxtFondo();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Dias Mora</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxtDiasMora();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Capital</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            @__ctrl5 = this.@__BuildControltxtCapital();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Monto Mora</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxtMontoMora();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Cuotas Pagadas</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            @__ctrl7 = this.@__BuildControltxtCuotasPagadas();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Saldo Certificado</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            @__ctrl8 = this.@__BuildControltxtSaldoCertificado();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Fogape(SM)</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            @__ctrl9 = this.@__BuildControltxtFogape();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                            <div class=""form-group"">
                                <label class=""col-sm-5 control-label"">Deuda CF / Valor Fondo</label>
                                <div class=""col-sm-7"">
                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            @__ctrl10 = this.@__BuildControltxtDeudaCF();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                        </div>

                        <div class=""col-md-6"">

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Giro</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl11;
            @__ctrl11 = this.@__BuildControltxtGiro();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Acreedor</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            @__ctrl12 = this.@__BuildControltxtAcreedor();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Tramo</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl13;
            @__ctrl13 = this.@__BuildControltxtTramo();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Intereses</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            @__ctrl14 = this.@__BuildControltxtIntereses();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Cuotas Mora</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl15;
            @__ctrl15 = this.@__BuildControltxtCuotasMora();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Cuotas Pactadas</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl16;
            @__ctrl16 = this.@__BuildControltxtCuotasPactadas();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Cuotas Pactasdas</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl17;
            @__ctrl17 = this.@__BuildControlTextBox2();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Garantia VA</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl18;
            @__ctrl18 = this.@__BuildControltxtGarantia();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">Deuda CF / Deuda Total</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl19;
            @__ctrl19 = this.@__BuildControlTextBox3();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>

                                <div class=""form-group"">
                                    <label class=""col-sm-5 control-label"">% Cobertura</label>
                                    <div class=""col-sm-7"">
                                        "));
            global::System.Web.UI.WebControls.TextBox @__ctrl20;
            @__ctrl20 = this.@__BuildControltxtCobertura();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>


                        </div>

                    </div>
                </div>


                <div class=""row"">
                    <div class=""col-md-12 col-sm-12"">
                        <h4>Contactos</h4>
                    </div>

                    <div class=""col-md-12"">
                        <table border=""0"" style=""table-layout: fixed; width: 100%;"">
                            <tr>
                                <td>
                                    <div class=""card-box"">
                                        <div class=""table-responsive"">
                                            "));
            global::System.Web.UI.WebControls.GridView @__ctrl21;
            @__ctrl21 = this.@__BuildControlgridContactos();
            @__parser.AddParsedSubObject(@__ctrl21);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>

                <!-- BOTONES -->
                <table width=""100%"">
                    <tr>
                        <td>
                            "));
            global::System.Web.UI.WebControls.Button @__ctrl22;
            @__ctrl22 = this.@__BuildControlbtnAtras();
            @__parser.AddParsedSubObject(@__ctrl22);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </td>\r\n                        <td></td>\r\n             " +
                        "       </tr>\r\n                </table>\r\n\r\n            </div>\r\n        </div>\r\n  " +
                        "  </div>\r\n\r\n\r\n\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::MultiRiesgo.wpDetalleCarteraMorosos.DetalleCarteraMorosos.DetalleCarteraMorosos @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<script type=\"text/javascript\">\r\n\r\n\r\n\r\n</script>\r\n\r\n\r\n "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldvWarning1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControldvFormulario();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
