//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiComercial.wpDirecciones.wpDirecciones {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class wpDirecciones {
        
        protected global::System.Web.UI.WebControls.Label lbWarning1;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvWarning1;
        
        protected global::System.Web.UI.WebControls.Label lbEmpresa;
        
        protected global::System.Web.UI.WebControls.Label lbRut;
        
        protected global::System.Web.UI.WebControls.Label lbEjecutivo;
        
        protected global::System.Web.UI.WebControls.LinkButton lbDatosEmpresa;
        
        protected global::System.Web.UI.WebControls.LinkButton lbHistoria;
        
        protected global::System.Web.UI.WebControls.LinkButton lbDocumentos;
        
        protected global::System.Web.UI.WebControls.LinkButton lbEmpresaRelacionada;
        
        protected global::System.Web.UI.WebControls.LinkButton lbDireccion;
        
        protected global::System.Web.UI.WebControls.LinkButton lbPersonas;
        
        protected global::System.Web.UI.WebControls.Label lbSuccess;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvSuccess;
        
        protected global::System.Web.UI.WebControls.Label lbWarning;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvWarning;
        
        protected global::System.Web.UI.WebControls.Label lbError;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvError;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlRegion;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlComunas;
        
        protected global::System.Web.UI.WebControls.TextBox txtNumero;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlVerificacion;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivVerificaion;
        
        protected global::System.Web.UI.WebControls.CheckBox chkprincipal;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlProvincia;
        
        protected global::System.Web.UI.WebControls.TextBox txtdireccion;
        
        protected global::System.Web.UI.WebControls.TextBox txtComplementoDireccion;
        
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl dtcFechaVerificacion;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivFechaVerificacion;
        
        protected global::System.Web.UI.WebControls.Panel pnFormulario;
        
        protected global::System.Web.UI.WebControls.Button btnAtras;
        
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        
        protected global::System.Web.UI.WebControls.GridView ResultadosBusqueda;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dv_buscarEmpresas;
        
        protected global::System.Web.UI.WebControls.HiddenField HddIdDireccionEmpresa;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvFormulario;
        
        public static implicit operator global::System.Web.UI.TemplateControl(wpDirecciones target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbWarning1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbWarning1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbWarning1";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvWarning1() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvWarning1 = @__ctrl;
            @__ctrl.ID = "dvWarning1";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-warning");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("role", "alert");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n     <h4>\r\n        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbWarning1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n     </h4>\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbEmpresa() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbEmpresa = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbEmpresa";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbRut() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbRut = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbRut";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbEjecutivo() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbEjecutivo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbEjecutivo";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbDatosEmpresa() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbDatosEmpresa = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbDatosEmpresa";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Datos Empresa"));
            @__ctrl.Click -= new System.EventHandler(this.lbDatosEmpresa_Click);
            @__ctrl.Click += new System.EventHandler(this.lbDatosEmpresa_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbHistoria() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbHistoria = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbHistoria";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Historia Empresa"));
            @__ctrl.Click -= new System.EventHandler(this.lbHistoria_Click);
            @__ctrl.Click += new System.EventHandler(this.lbHistoria_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbDocumentos() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbDocumentos = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbDocumentos";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Documentos"));
            @__ctrl.Click -= new System.EventHandler(this.lbDocumentos_Click);
            @__ctrl.Click += new System.EventHandler(this.lbDocumentos_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbEmpresaRelacionada() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbEmpresaRelacionada = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbEmpresaRelacionada";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Empresas Relacionadas"));
            @__ctrl.Click -= new System.EventHandler(this.lbEmpresaRelacionada_Click);
            @__ctrl.Click += new System.EventHandler(this.lbEmpresaRelacionada_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbDireccion() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbDireccion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbDireccion";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Direcciones"));
            @__ctrl.Click -= new System.EventHandler(this.lbDireccion_Click);
            @__ctrl.Click += new System.EventHandler(this.lbDireccion_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbPersonas() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbPersonas = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbPersonas";
            @__ctrl.OnClientClick = "return Dialogo();";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Personas"));
            @__ctrl.Click -= new System.EventHandler(this.lbPersonas_Click);
            @__ctrl.Click += new System.EventHandler(this.lbPersonas_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbSuccess() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbSuccess = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbSuccess";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvSuccess() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvSuccess = @__ctrl;
            @__ctrl.ID = "dvSuccess";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-success");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <h4>\r\n                            "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbSuccess();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </h4>\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbWarning() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbWarning = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbWarning";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvWarning() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvWarning = @__ctrl;
            @__ctrl.ID = "dvWarning";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-warning");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("role", "alert");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <h4>\r\n                            "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbWarning();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </h4>\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbError";
            @__ctrl.Text = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvError() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvError = @__ctrl;
            @__ctrl.ID = "dvError";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "alert alert-danger");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <h4>\r\n                            "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbError();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </h4>\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlTipo() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlTipo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlTipo";
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlRegion() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlRegion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlRegion";
            @__ctrl.AutoPostBack = true;
            @__ctrl.CssClass = "form-control";
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlRegion_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlRegion_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlComunas() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlComunas = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlComunas";
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtNumero() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtNumero = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtNumero";
            @__ctrl.CssClass = "form-control";
            @__ctrl.MaxLength = 50;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlVerificacion() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlVerificacion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlVerificacion";
            @__ctrl.CssClass = "form-control";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlDivVerificaion() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.DivVerificaion = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-group row");
            @__ctrl.ID = "DivVerificaion";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                <label for=\"chkprincipal\" class" +
                        "=\"col-sm-5 control-label\">Verificación:</label>\r\n                               " +
                        "                 <div class=\"col-sm-7\">\r\n                                       " +
                        "             "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControlddlVerificacion();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                </div>\r\n                       " +
                        "                     "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchkprincipal() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            this.chkprincipal = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "chkprincipal";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlProvincia() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlProvincia = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlProvincia";
            @__ctrl.CssClass = "form-control";
            @__ctrl.AutoPostBack = true;
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlProvincia_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlProvincia_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtdireccion() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtdireccion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtdireccion";
            @__ctrl.CssClass = "form-control";
            @__ctrl.MaxLength = 250;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtComplementoDireccion() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtComplementoDireccion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtComplementoDireccion";
            @__ctrl.CssClass = "form-control";
            @__ctrl.MaxLength = 250;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControldtcFechaVerificacion() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.dtcFechaVerificacion = @__ctrl;
            @__ctrl.ID = "dtcFechaVerificacion";
            @__ctrl.Calendar = global::Microsoft.SharePoint.SPCalendarType.Gregorian;
            @__ctrl.LocaleId = 13322;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.EnableViewState = true;
            @__ctrl.DateOnly = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlDivFechaVerificacion() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.DivFechaVerificacion = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-group row");
            @__ctrl.ID = "DivFechaVerificacion";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                <label for=""txt_nombre"" class=""col-sm-5 control-label"">Fecha Verificación:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldtcFechaVerificacion();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                </div>\r\n                       " +
                        "                     "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnFormulario() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnFormulario = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnFormulario";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        <!-- Grupo 1 -->
                                        <div class=""col-md-6"">
                                            <div class=""form-group row"">
                                                <label for=""txt_rut"" class=""col-sm-5 control-label"">Tipo:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControlddlTipo();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                </div>
                                            </div>

                                            <div class=""form-group row"">
                                                <label for=""txt_correo"" class=""col-sm-5 control-label"">Región:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            @__ctrl2 = this.@__BuildControlddlRegion();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                </div>
                                            </div>

                                            <div class=""form-group row"">
                                                <label for=""txt_nombre"" class=""col-sm-5 control-label"">Comuna:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControlddlComunas();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                </div>
                                            </div>

                                            <div class=""form-group row"">
                                                <label for=""txt_nombre"" class=""col-sm-5 control-label"">Número:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxtNumero();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                </div>\r\n                       " +
                        "                     </div>\r\n\r\n                                            "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl5;
            @__ctrl5 = this.@__BuildControlDivVerificaion();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        </div>
                                        <!-- Grupo 2 -->
                                        <div class=""col-md-6"">
                                            <div class=""form-group row"">
                                                <label for=""txt_apellidos"" class=""col-sm-5 control-label"">Principal:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::System.Web.UI.WebControls.CheckBox @__ctrl6;
            @__ctrl6 = this.@__BuildControlchkprincipal();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                </div>
                                            </div>

                                            <div class=""form-group row"">
                                                <label for=""txt_nombre"" class=""col-sm-5 control-label"">Provincia:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl7;
            @__ctrl7 = this.@__BuildControlddlProvincia();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                </div>
                                            </div>

                                            <div class=""form-group row"">
                                                <label for=""txt_nombre"" class=""col-sm-5 control-label"">Calle:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            @__ctrl8 = this.@__BuildControltxtdireccion();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                </div>
                                            </div>

                                            <div class=""form-group row"">
                                                <label for=""txt_nombre"" class=""col-sm-5 control-label"">Complemento Dirección:</label>
                                                <div class=""col-sm-7"">
                                                    "));
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            @__ctrl9 = this.@__BuildControltxtComplementoDireccion();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                </div>\r\n                       " +
                        "                     </div>\r\n\r\n                                            "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl10;
            @__ctrl10 = this.@__BuildControlDivFechaVerificacion();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        </div>\r\n                               " +
                        "     "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnAtras() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnAtras = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnAtras";
            @__ctrl.CssClass = "btn btn-default pull-left";
            @__ctrl.Text = " < Volver Atrás";
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnAtras_Click);
            @__ctrl.Click += new System.EventHandler(this.btnAtras_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancelar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancelar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancelar";
            @__ctrl.Text = "Cancelar";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary pull-right");
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnAtras_Click);
            @__ctrl.Click += new System.EventHandler(this.btnAtras_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel";
            @__ctrl.Text = "Limpiar";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-warning pull-right");
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnGuardar() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnGuardar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary btn-success pull-right");
            @__ctrl.ID = "btnGuardar";
            @__ctrl.Text = "Guardar";
            @__ctrl.OnClientClick = "return Dialogo();";
            @__ctrl.Click -= new System.EventHandler(this.btnGuardar_Click);
            @__ctrl.Click += new System.EventHandler(this.btnGuardar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlResultadosBusqueda() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.ResultadosBusqueda = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ResultadosBusqueda";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "table table-bordered table-hover");
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Horizontal;
            @__ctrl.RowHeaderColumn = "0";
            @__ctrl.ShowHeaderWhenEmpty = true;
            @__ctrl.PageSize = 5;
            @__ctrl.ViewStateMode = global::System.Web.UI.ViewStateMode.Enabled;
            @__ctrl.RowCreated -= new System.Web.UI.WebControls.GridViewRowEventHandler(this.ResultadosBusqueda_RowCreated);
            @__ctrl.RowCreated += new System.Web.UI.WebControls.GridViewRowEventHandler(this.ResultadosBusqueda_RowCreated);
            @__ctrl.RowDataBound -= new System.Web.UI.WebControls.GridViewRowEventHandler(this.ResultadosBusqueda_RowDataBound);
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.ResultadosBusqueda_RowDataBound);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldv_buscarEmpresas() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dv_buscarEmpresas = @__ctrl;
            @__ctrl.ID = "dv_buscarEmpresas";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "row clearfix");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                                <div class=\"col" +
                        "-md-12 column\">\r\n                                                               " +
                        "     "));
            global::System.Web.UI.WebControls.GridView @__ctrl1;
            @__ctrl1 = this.@__BuildControlResultadosBusqueda();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                                </div>\r\n       " +
                        "                                                     "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHddIdDireccionEmpresa() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.HddIdDireccionEmpresa = @__ctrl;
            @__ctrl.ID = "HddIdDireccionEmpresa";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldvFormulario() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.dvFormulario = @__ctrl;
            @__ctrl.ID = "dvFormulario";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

    <!-- Page-Title -->
    <div class=""row marginInicio"">
        <div class=""col-sm-12"">
            <h4 class=""page-title"">Direcciones</h4>
            <ol class=""breadcrumb"">
                <li>
                    <a href=""#"">Datos empresa</a>
                </li>
                <li class=""active"">Direcciones
                </li>
            </ol>
        </div>
    </div>

    <!-- Empresa -->
    <div class=""row"">
        <div class=""col-md-12"">
            <div class=""alert alert-gray"">
                <p>
                    <strong>Empresa:
                "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbEmpresa();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</strong> /\r\n                "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllbRut();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    \r\n                / Ejecutivo:\r\n                "));
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControllbEjecutivo();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                </p>
            </div>
        </div>
    </div>

    <!-- Contenedor Tabs -->
    <div class=""row"">
        <div class=""col-md-12"">
            <ul class=""nav nav-tabs navtab-bg nav-justified"">
                <li class="""">
                    <a href=""#tab1"" data-toggle=""tab"" aria-expanded=""false"">
                        <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                        <span class=""hidden-xs"">
                            "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl4;
            @__ctrl4 = this.@__BuildControllbDatosEmpresa();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </span>
                    </a>
                </li>
                <li class="""">
                    <a href=""#tab2"" data-toggle=""tab"" aria-expanded=""false"">
                        <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                        <span class=""hidden-xs"">
                            "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl5;
            @__ctrl5 = this.@__BuildControllbHistoria();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </span>
                    </a>
                </li>
                <li class="""">
                    <a href=""#tab3"" data-toggle=""tab"" aria-expanded=""false"">
                        <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                        <span class=""hidden-xs"">
                            "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl6;
            @__ctrl6 = this.@__BuildControllbDocumentos();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </span>
                    </a>
                </li>
                <li class="""">
                    <a href=""#tab4"" data-toggle=""tab"" aria-expanded=""false"">
                        <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                        <span class=""hidden-xs"">
                            "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl7;
            @__ctrl7 = this.@__BuildControllbEmpresaRelacionada();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </span>
                    </a>
                </li>
                <li class=""active"">
                    <a href=""#tab5"" data-toggle=""tab"" aria-expanded=""true"">
                        <span class=""visible-xs""><i class=""fa fa-home""></i></span>
                        <span class=""hidden-xs"">
                            "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl8;
            @__ctrl8 = this.@__BuildControllbDireccion();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </span>
                    </a>
                </li>
                <li class="""">
                    <a href=""#tab6"" data-toggle=""tab"" aria-expanded=""false"">
                        <span class=""visible-xs""><i class=""fa fa-user""></i></span>
                        <span class=""hidden-xs"">
                            "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl9;
            @__ctrl9 = this.@__BuildControllbPersonas();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </span>\r\n                    </a>\r\n                </li" +
                        ">\r\n            </ul>\r\n\r\n            <div class=\"tab-content\">\r\n                <" +
                        "div class=\"tab-pane active\" id=\"tab5\">\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl10;
            @__ctrl10 = this.@__BuildControldvSuccess();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl11;
            @__ctrl11 = this.@__BuildControldvWarning();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl12;
            @__ctrl12 = this.@__BuildControldvError();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                    <div class=\"row\">\r\n                        <div class=\"co" +
                        "l-md-12\">\r\n                            <div class=\"card-box\">\r\n                 " +
                        "               <div class=\"row\">\r\n                                    "));
            global::System.Web.UI.WebControls.Panel @__ctrl13;
            @__ctrl13 = this.@__BuildControlpnFormulario();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                                <div class=""row"">
                                    <div class=""col-md-12"">
                                        <br>
                                        <table style=""width:100%"">
                                            <tr>
                                                <td>
                                                    "));
            global::System.Web.UI.WebControls.Button @__ctrl14;
            @__ctrl14 = this.@__BuildControlbtnAtras();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                </td>\r\n                        " +
                        "                        <td>\r\n                                                  " +
                        "  "));
            global::System.Web.UI.WebControls.Button @__ctrl15;
            @__ctrl15 = this.@__BuildControlbtnCancelar();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                    "));
            global::System.Web.UI.WebControls.Button @__ctrl16;
            @__ctrl16 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                    "));
            global::System.Web.UI.WebControls.Button @__ctrl17;
            @__ctrl17 = this.@__BuildControlbtnGuardar();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                </td>
                                            </tr>
                                        </table>
                                        <br>
                                        <table border=""0"" style=""table-layout: fixed; width: 100%;"">
                                            <tr>
                                                <td>
                                                    <div class=""card-box"">
                                                        <div class=""table-responsive"">
                                                            "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl18;
            @__ctrl18 = this.@__BuildControldv_buscarEmpresas();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl19;
            @__ctrl19 = this.@__BuildControlHddIdDireccionEmpresa();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::MultiComercial.wpDirecciones.wpDirecciones.wpDirecciones @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<style type=""text/css"">
    .form-group label {
        text-align:right;
        padding-top:10px;
    }
    td{
        white-space:normal;
    }
</style>

<script src=""../../_layouts/15/MultiComercial/FuncionesClientes.js""></script>
<script src=""../../_layouts/15/MultiComercial/jquery-1.11.1.js""></script>


<script type=""text/javascript"">
    $(document).ready(function () {
        $(""td.ms-dtinput a"").addClass(""btn btn-default"").html(""<i class='icon-calender'></i>"");
    });

</script>

"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldvWarning1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControldvFormulario();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
