//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiAdministracion.wpTest.wpTest {
    using System.Web.UI.WebControls.Expressions;
    using System.Collections;
    using System.Text;
    using DevExpress.Web;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    
    
    public partial class wpTest {
        
        protected global::System.Web.UI.WebControls.GridView myGridWiew;
        
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourcePerfiles;
        
        public static implicit operator global::System.Web.UI.TemplateControl(wpTest target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlmyGridWiew() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.myGridWiew = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "myGridWiew";
            @__ctrl.DataSourceID = "SqlDataSourcePerfiles";
            @__ctrl.AutoGenerateColumns = true;
            @__ctrl.CssClass = "table table-bordered table-hover table-responsive";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.SqlDataSource @__BuildControlSqlDataSourcePerfiles() {
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.SqlDataSource();
            this.SqlDataSourcePerfiles = @__ctrl;
            @__ctrl.ID = "SqlDataSourcePerfiles";
            @__ctrl.SelectCommand = "select top 10 *, *, * from view_perfiles order by 3, 4, 5, 6, 7";
            @__ctrl.SelectCommandType = global::System.Web.UI.WebControls.SqlDataSourceCommandType.Text;
            @__ctrl.ConnectionString = global::System.Convert.ToString(System.Web.Compilation.ConnectionStringsExpressionBuilder.GetConnectionString("DACConnectionString"), global::System.Globalization.CultureInfo.CurrentCulture);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::MultiAdministracion.wpTest.wpTest.wpTest @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n\r\n\r\n    <!-- tabla / grilla -->\r\n   \n    <div class=\"row\">            \t\t\t" +
                        "\t\t\t\n        <div class=\"col-md-12\">\n            <div class=\"card-box\">\n         " +
                        "      \n                    "));
            global::System.Web.UI.WebControls.GridView @__ctrl1;
            @__ctrl1 = this.@__BuildControlmyGridWiew();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t  \n            </div>\n        </div>\n    </div>\n   \n    \n    "));
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl2;
            @__ctrl2 = this.@__BuildControlSqlDataSourcePerfiles();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
